dataset: torch/image_folder
num_classes: 200
train_split: train
val_split: valid
img_size: 64
mean:
    - 0.480
    - 0.448
    - 0.397
std:
    - 0.272
    - 0.265
    - 0.274
crop_pct: 0.9
scale:
    - 0.08
    - 1.0
interpolation: bicubic
train_interpolation: random
aa: rand-m9-mstd0.5-inc1
mixup: 0.8
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 1.0
reprob: 0.25
remode: pixel
amp: True
batch_size: 64
lr: 0.0005
min_lr: 0.00001
sched: cosine
weight_decay: 5e-2
epochs: 1
cooldown_epochs: 10
warmup_epochs: 10
warmup_lr: 0.000001
opt: adamw
smoothing: 0.1
workers: 4
use_kd: true
kd_alpha: 4
seed: 3407
checkpoint_hist: 3
fix_blocksize: 1
# Setting the budget to 2,4,8 to calculate the configuration whose latency is equal to uniform block sizes 2,4,8
budget: 8
# better_initialization is true means using our initialization method, false means using previous "min |W'-W|^2" method
better_initialization: True
log_name: vit_tiny_ILP_test
teacher: vit_9_12_64
teacher_checkpoint: pretrained/vit_tiny.pth.tar
initial_checkpoint: pretrained/vit_tiny.pth.tar